import React from 'react'
import styled from 'styled-components'

import Video from "../assets/videos/travel_5.mp4"
import Form from './Form';
const Hero = () => {
   
            return( <HeroContainer>
            <HeroBg>
                <VideoBg src={Video} type="video/mp4"
                autoPlay loop muted playsInline></VideoBg>
            </HeroBg>
            <HeroContent>
                <HeroItems >
                    <HeroH1 >TRAVEL COMPANY</HeroH1>
                    <HeroP >it is better to travel well than to arrive</HeroP>
                
               <Form/> </HeroItems>
               
            </HeroContent>
             
        </HeroContainer>);
        
       
            
}

export default Hero

const HeroContainer = styled.div`
background: #0c0c0c;
display: flex;
justify-content: center;
color: #fff;
align-items: center;
height: 100vh;
padding: 0 1rem;
position: relative;
margin-top: -80px;
`
const HeroBg = styled.div`
position: absolute;
top: 0;
bottom: 0;
right: 0;
left: 0;
width: 100%;
height: 100%;
overflow: hidden;
`
const VideoBg = styled.video`
width: 100%;
height:100%;
-o-object-fit: cover;
object-fit: cover;
filter: brightness(0.5);
`
const HeroContent = styled.div`
z-index: 3;
height: calc(100vh - 80px);
max-height: 100%;
padding: 0rem calc((100vw - 1300px) / 2);



`
const HeroItems = styled.div`
display: flex;
flex-direction: column;
justify-content: center;
align-items: center;
text-align: center;
height: 100vh;
max-height: 100%;
padding: 0;
color: #fff;
line-height: 1.1;
font-weight: bold;
`
const HeroH1 = styled.h1`
font-size: clamp(1.5rem, 6vw, 6rem);
margin-bottom: 1.5rem;
letter-spacing: 4px;
padding: 0 1rem;
font-family: "Roboto", sans-serif;
font-weight: 400;
text-shadow: 2px 2px rgba(0,0,0,0.3);


-webkit-animation: focus-in-expand-fwd 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
animation: focus-in-expand-fwd 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

/* ----------------------------------------------
 * Generated by Animista on 2021-2-1 13:8:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}

`
const HeroP = styled.p`
font-size: clamp(1rem, 3vw, 3rem);
margin-bottom: 2rem;
font-weight:200;
font-family: "Montserrat", sans-serif;


-webkit-animation: focus-in-expand-fwd 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
animation: focus-in-expand-fwd 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

/* ----------------------------------------------
 * Generated by Animista on 2021-2-1 13:8:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}

@media screen and (max-width: 767px){
  margin-bottom: 10rem;
}`